### ISSUE TITLE
New version of dotnet-sdk3-1-400 on M1 fix

### ISSUE THREAD

**Issue by ruxavik** [isen-ng/homebrew-dotnet-sdk-versions#182] opened 2021-11-16 01:42 UTC
New updated builds for dotnet-sdk3-1-400 put binaries setup to different directory now on M1 Mac:
`/usr/local/share/dotnet/x64`
and because only arm64 SDKs are added to the "path". 
**dotnet** command is not found after installation. 
explicitly call /usr/local/share/dotnet/x64/dotnet or add hint to users to modify PATH 
`export PATH="/usr/local/share/dotnet/x64:$PATH"`

**Comment by isen-ng** [comment] 2021-11-16 06:56
Let me confirm the behaviour once I get hold of a mac

**Comment by orrpan** [comment] 2021-11-16 08:29
![image](https://user-images.githubusercontent.com/5699172/141948667-7453d5d7-4976-45f4-a20b-c6c6014d72bc.png)

This is how it will install it since the latest binaries. Blue arm64, purple x64.

**Comment by isen-ng** [comment] 2021-11-16 09:45
oh awesome! Thanks @orrpan 

It's been a while, so need to verify some behaviour about getting brew to automatically link the binary (and the behaviour of multiple conflicting links). Let me test that.

**Comment by isen-ng** [comment] 2021-11-17 02:29
This should be fixed now in #184.
I've forcefully add a symlink to the dotnet binary even if it exists by using postflight and a script.

**Comment by ruxavik** [comment] 2021-11-17 03:47
Let's say if I installed .NET 6 and than 3.1. will it just symlink older version of dotnet ?

**Comment by isen-ng** [comment] 2021-11-17 03:56
there is "no older version" of dotnet. The `dotnet` executable is the same one for all versions. That's why when you do `dotnet --list-sdk` you get all the installed sdks.

However, your example is an interesting one. Because .NET 6 might be an arm64 executable, and .NET 3.1 will be a x64 executable. Eg, there are 2 `dotnet` executables installed, 

1. `/usr/local/share/dotnet/dotnet` for sdks that support arm64
2. `/usr/local/share/dotnet/x64/dotnet` for sdks that only supoport x64

I wonder what happens you are on an arm64 machine, and runs the x64 version of `dotnet` (eg `/usr/local/share/dotnet/x64/dotnet`). If there are no issues, then we are happy.

However, if there are issues, I think it might be wayyyyy out of the scope of this tap to detect the many conditions that result in this situation (eg using both x64 and arm64 sdks on an M1 machine).

**Comment by PSanetra** [comment] 2021-11-17 18:07
@isen-ng this is exactly my current situation. I have installed .NET 6 for arm64 and .NET 5 and 3.1 for x64.

These are the results:
```
❯ /usr/local/share/dotnet/x64/dotnet --list-sdks
3.1.415 [/usr/local/share/dotnet/x64/sdk]
5.0.403 [/usr/local/share/dotnet/x64/sdk]
❯ /usr/local/share/dotnet/dotnet --list-sdks
6.0.100 [/usr/local/share/dotnet/sdk]
```

So both dotnet executables find only the sdks belonging to their specific architecture.

Do you have an idea how to fix this situation?

**Comment by isen-ng** [comment] 2021-11-18 06:20
The idea is

1. the `dotnet` executable is already symlinked by the installer package
    - there's no need to do it in the cask
2. the `dotnet` executable IS NOT symlinked by the installer package when
    - the installer is x64 and the host machine is arm64
    - this is by design, decided by the dotnet-core developers

So what I'm going to do is to symlink the x64 `dotnet` as `dotnetx64` when the host machine is an arm64 machine.
what do you guys this?

**Comment by PSanetra** [comment] 2021-11-18 08:26
@isen-ng Sounds like a good aproach for the long term solution. :+1: 

I am wondering if it is possible to force brew to install also the x64 version of the sdk when the arm64 is already supported by that sdk version. There might be some edge cases where I am not able to use the arm64 sdk for now: e.g. https://github.com/confluentinc/confluent-kafka-dotnet/issues/1707

**Comment by isen-ng** [comment] 2021-11-18 08:51
Installing both x64 and arm64? I haven't tried that before but you can tell your M1 mac to pretend that is `x86_64`:
https://stackoverflow.com/questions/64951024/how-can-i-run-two-isolated-installations-of-homebrew

Other than that, I have no idea how homebrew itself would behave. It would likely complain about how the cask you're trying to install, already exists. The SO answer does present something interesting: installing `brew` and `brow`. Use `brew` to install arm64 of the sdk, and use `brow` to install x64 of the sdk.

**Comment by orrpan** [comment] 2021-11-18 13:55
One solution could be to have a cask called dotnet-sdk6-...arm64_and_x64 which installs both. For now I'm using pkg download with x64 6.0 and cask for arm64 6.0, 3.1 and 5.0. I havn't been able to make dotnet solutions play nice with projects using different sdks if they are not the same arch. For new project without any old 3.1 and 5.0 I use the 6.0 arm64...

**Comment by isen-ng** [comment] 2021-11-22 02:46
Hmm I think I'll probably not implement this double installation cask. Reason being, if someone needs a x64 pkg on a arm64 machine, personally, I think their problem might be much bigger than just the dotnet-sdk cask, they will likely need to install a host of other x64 formulas and casks. In light of that, I think installing a x64 version of homebrew (brow) will be a better solution

**Closed** 2021-11-22 02:46 UTC
